// <auto-generated />
using System;
using CodeDiffPrompt.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeDiffPrompt.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251015142958_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("CodeDiffPrompt.Web.Data.CodeSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CodeSnapshots");
                });

            modelBuilder.Entity("CodeDiffPrompt.Web.Data.PromptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AfterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BeforeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiffText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmResponse")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AfterId");

                    b.HasIndex("BeforeId");

                    b.ToTable("PromptRecords");
                });

            modelBuilder.Entity("CodeDiffPrompt.Web.Data.PromptRecord", b =>
                {
                    b.HasOne("CodeDiffPrompt.Web.Data.CodeSnapshot", "After")
                        .WithMany()
                        .HasForeignKey("AfterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CodeDiffPrompt.Web.Data.CodeSnapshot", "Before")
                        .WithMany()
                        .HasForeignKey("BeforeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("After");

                    b.Navigation("Before");
                });
#pragma warning restore 612, 618
        }
    }
}
